language: java
jdk:
  - openjdk8
  - oraclejdk11
matrix:
  include:
    - jdk: oraclejdk11
      env: COVERALLS=true
after_success:
  - test -z $COVERALLS || mvn clean test jacoco:report coveralls:report
